Change from MD5 to SHA256 digests
Newer versions of Puppet does not support MD5.
# puppet cert sign dashboard
Error: unknown message digest algorithm